### ISSUE TITLE
Example functional of connect-mssql + node-mssql + passport

### ISSUE THREAD

**Issue by estvmachine** [patriksimek/connect-mssql#4]
Hi , I will not be obsessive but could you give me a functional example of  **"connect-mssql + node-mssql + passport"**. I would be very grateful and maybe can resolve my problem. Or maybe a good implementation of the 'node-mssql' with passport **without the sessions**, only the part of the 'strategy'. Something like this:

```javascript
passport.use('mssql', new LocalStrategy(
		{
			usernameField: 'username',
			passwordField: 'password', 
            passReqToCallback: true
		},
		function(req, username, password, done) {

			  //METHOD OF CONNECTION USING NODE-MSSQL 

	    } 

	)); // end passport.use(...)
```

**Comment by patriksimek** [comment]
Unfortunately I can't because I have never used passport before. Maybe someone else did.

**Comment by estvmachine** [comment]
If you want to do a implementation of node-mssql, what type of configuration you do for example obtain for your projects?. Actually i having a single file where open a connection and make the sql.execution, im using this for Express using the pipe, something like this:

app.get('/users',  mssql.executeQuery, users.list)

Im doing this way because if i wanna use it in the same method of users.list in this example, i cant get the answer, i think im doing something wrong from this level.

**Comment by estvmachine** [comment]
Well at least the express sessions and connect- express work smoothly, i write the sessions in my SQL Server

**Comment by estvmachine** [comment]
I resolve my problem, using promise and a global configuration in the root of my app. Thanks
